name: Zip and Pre-Release

on:
  push:
    tags:
      - 'v*.*.*-pre-*'

jobs:

  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive Release1
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'development_behavior_packs/NiaServer-Core-BP'
          path: '.'
          filename: NiaServer-Core-BP-${{ github.ref_name }}.zip
      - name: Upload the behavior_pack
        uses: actions/upload-artifact@v4
        with:
          name: NiaServer-Core-BP-${{ github.ref_name }}.zip
          path: ./development_behavior_packs/NiaServer-Core-BP/NiaServer-Core-BP-${{ github.ref_name }}.zip
      - name: Archive Release2
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'development_resource_packs/NiaServer-Core-RP'
          path: '.'
          filename: NiaServer-Core-RP-${{ github.ref_name }}.zip
      - name: Upload the resource_pack
        uses: actions/upload-artifact@v4
        with:
          name: NiaServer-Core-RP-${{ github.ref_name }}.zip
          path: ./development_resource_packs/NiaServer-Core-RP/NiaServer-Core-RP-${{ github.ref_name }}.zip

  release:
    needs: [zip]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download the behavior_pack
        uses: actions/download-artifact@v4
        with:
          name: NiaServer-Core-BP-${{ github.ref_name }}.zip
      - name: Download the resource_pack
        uses: actions/download-artifact@v4
        with:
          name: NiaServer-Core-RP-${{ github.ref_name }}.zip
      - name: Create and upload release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          artifacts: "NiaServer-Core-BP-${{ github.ref_name }}.zip,NiaServer-Core-RP-${{ github.ref_name }}.zip,world_behavior_packs.json,world_resource_packs.json"
          bodyFile: "CHANGELOG-PRE.md"
          generateReleaseNotes: false
          token: ${{ secrets.GITHUB_TOKEN }}
